### ISSUE TITLE
CPU Pegged when running as a GUI

### ISSUE THREAD

**Issue by paul-way** [morpheums/Binance.API.Csharp.Client#14]
Thank you for writing this client!  I am able to connect when I use the console; however, when I use a Win Forms or WPF, it seems to stall and lock the CPU.  Any ideas?

![image](https://user-images.githubusercontent.com/1904763/34449672-ec3ae8a6-ecc8-11e7-981e-6a97fa90e6aa.png)
![image](https://user-images.githubusercontent.com/1904763/34449678-04758c3c-ecc9-11e7-9b20-f51852706ef8.png)

**Comment by adomorn** [comment]
same issue here

**Comment by morpheums** [comment]
The problem is that you are locking the UI thread by calling it that way from your method, there are 2 options to avoid Deadlocks, the first option you must mark your method with the **"async"** modifier, the second you just have to use **"Task.Run"**:

- Option 1 (Using the **"async"** method): `var serverTime = await binanceClient.GetAllPrices()`

- Option 2: `var serverTime = Task.Run(() => binanceClient.GetServerTime()).Result;`

Please let me know if this worked for you so i can close the ticket, thanks!

**Comment by paul-way** [comment]
That worked perfectly for me.  I figured it was something I was doing.  Thanks for the quick response!
